# Generated by Django 5.2.5 on 2025-08-31 15:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Membru',
            fields=[
                ('idmembru', models.AutoField(primary_key=True, serialize=False)),
                ('nume', models.CharField(db_column='Nume', max_length=100)),
                ('prenume', models.CharField(db_column='Prenume', max_length=100)),
                ('cnp', models.CharField(db_column='CNP', max_length=15)),
                ('adresa', models.CharField(db_column='Adresa', max_length=255)),
            ],
            options={
                'verbose_name': 'Membru',
                'verbose_name_plural': 'Membri',
                'db_table': 'membri',
            },
        ),
        migrations.CreateModel(
            name='Trupa',
            fields=[
                ('idtrupa', models.AutoField(primary_key=True, serialize=False)),
                ('numetrupa', models.CharField(db_column='NumeTrupa', max_length=100)),
                ('genmuzical', models.CharField(db_column='GenMuzical', max_length=50)),
                ('aninfiintare', models.CharField(db_column='AnInfiintare', max_length=4)),
                ('tara', models.CharField(db_column='Tara', max_length=50)),
            ],
            options={
                'verbose_name': 'Trupa',
                'verbose_name_plural': 'Trupe',
                'db_table': 'trupe',
            },
        ),
        migrations.CreateModel(
            name='MembruTrupa',
            fields=[
                ('idmembritrupe', models.AutoField(primary_key=True, serialize=False)),
                ('rol', models.CharField(db_column='Rol', max_length=50)),
                ('datainscriere', models.CharField(db_column='DataInscriere', max_length=12)),
                ('activitate', models.CharField(db_column='Activitate', max_length=20)),
                ('membru', models.ForeignKey(db_column='idmembru', on_delete=django.db.models.deletion.CASCADE, to='crud_app.membru')),
                ('trupa', models.ForeignKey(db_column='idtrupa', on_delete=django.db.models.deletion.CASCADE, to='crud_app.trupa')),
            ],
            options={
                'verbose_name': 'Membru Trupa',
                'verbose_name_plural': 'Membri Trupe',
                'db_table': 'membritrupe',
                'unique_together': {('membru', 'trupa')},
            },
        ),
    ]
